name: DATABASE ping
on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:      # Allows you to run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping MySQL
        run: |
          mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SELECT 1;"
